name: e2e-scheduled

on:
  schedule:
    - cron: '0 */6 * * *'    # 6 saatte bir (UTC). İstanbul için +3 saat farkı düşün.
  workflow_dispatch: {}

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - run: npm ci

      # Testi çalıştır. Çıkış kodunu yakala ki hata olursa bildirime geçelim.
      - name: Run Cypress
        id: run
        shell: bash
        env:
          CY_BASE_URL: ${{ secrets.CY_BASE_URL }}
          CY_WEBHOOK_BASE: ${{ secrets.CY_WEBHOOK_BASE }}
        run: |
          set +e
          npx cypress run --reporter junit --reporter-options "mochaFile=reports/junit/results-[hash].xml"
          STATUS=$?
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          exit 0

      - name: Upload artifacts (screenshots/videos/reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            reports

      # 🔔 Google Chat bildirimi (sadece hata olursa)
      - name: Notify Google Chat on failure
        if: steps.run.outputs.status != '0'
        env:
          CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          MSG=$(cat <<'EOF'
          {
            "text": "🚨 *Cypress scheduled run FAILED*\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nRun: ${RUN_URL}"
          }
          EOF
          )
          curl -s -X POST -H "Content-Type: application/json" -d "$MSG" "$CHAT_WEBHOOK"
